#!/bin/sh
# postrm script for nest
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
	remove|abort-install)
		# the directories will not be removed if they are not empty
		if [ -d /var/log/personalfme ]; then
			rmdir --ignore-fail-on-non-empty /var/log/personalfme
		fi	
		if [ -d /var/lib/personalfme ]; then
			rmdir --ignore-fail-on-non-empty /var/lib/personalfme
		fi

		# mask the daemon
		if [ -d /run/systemd/system ]; then
		    systemctl --system daemon-reload >/dev/null || true
		fi
		if [ -x "/usr/bin/deb-systemd-helper" ]; then
			deb-systemd-helper mask personalfme.service >/dev/null
		fi
		;;

	upgrade|purge|abort-upgrade|failed-upgrade|disappear)
		# remove the daemon
		if [ -d /run/systemd/system ]; then
		    systemctl --system daemon-reload >/dev/null || true
		fi		
		if [ -x "/usr/bin/deb-systemd-helper" ]; then
			deb-systemd-helper purge personalfme.service >/dev/null
			deb-systemd-helper unmask personalfme.service >/dev/null
		fi
		exit 0
		;;
		
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1

esac

exit 0
