#!/bin/sh
# preinst script for nest
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
#
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
		mkdir -p /var/log/personalfme
		chmod 0777 /var/log/personalfme

		mkdir -p /var/lib/personalfme
		chmod 0777 /var/lib/personalfme
		;;

    abort-upgrade)
    	;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
